"UPDATE DATA: Thu Mar 16 2017 17:10:07 GMT+0800 (CST)" 
{
"name":"es6-magazine",
"version":"1.0.0-csp",
"description":"A es6-magazine project",
"scripts":{"dev":"node build/dev/index.js",
"build":"node build/build/index.js",
"build:widget":"node build/build/compiler.widget.js",
"copy":"node build/copy/index.js",
"remote":"node build/remote/index.js",
"lint":"eslint dist/xxtppt.dev.js",
"unit":"karma start test/unit/karma.conf.js",
"karma":"karma start karma.conf.js --log-level debug --single-run",
"git":"bash build/shell/git.sh",
"svn":"node build/shell/svn.js",
"test":"node build/template/test.js",
"release":"node build/template/release.code.js",
"ncu":"node build/ncu.package.js",
"format":"node build/format.js",
"check":"flow; test $? -eq 0 -o $? -eq 2",
"flow:check":"flow check"
},
"repository":{"type":"git",
"url":"git+https://github.com/JsAaron/node-magazine.git"},
"author":"Aaron",
"license":"ISC",
"bugs":{"url":"https://github.com/JsAaron/node-magazine/issues"},
"homepage":"https://github.com/JsAaron/node-magazine#readme",
"devDependencies":{"ssh2":"^0.5.4",
"underscore":"^1.8.3",
"colors":"^1.1.2",
"browser-sync":"^2.18.8",
"express":"^4.15.2",
"flow-bin":"^0.41.0",
"open":"0.0.5",
"fs-extra":"^2.1.1",
"npm-check-updates":"^2.10.3",
"babel-eslint":"^7.1.1",
"babel-loader":"^6.4.1",
"babel-plugin-external-helpers":"^6.22.0",
"babel-plugin-transform-flow-strip-types":"^6.22.0",
"babel-preset-es2015":"^6.24.0",
"eslint":"^3.17.1",
"eslint-friendly-formatter":"^2.0.7",
"eslint-loader":"^1.6.3",
"eslint-plugin-promise":"^3.5.0",
"eslint-plugin-standard":"^2.1.1",
"eventsource-polyfill":"^0.9.6",
"gulp":"^3.9.1",
"gulp-autoprefixer":"^3.1.1",
"gulp-clean-css":"^3.0.3",
"gulp-concat":"^2.6.1",
"gulp-rename":"^1.2.2",
"gulp-uglify":"^2.1.0",
"gulp-watch":"^4.3.11",
"rollup":"^0.41.6",
"rollup-plugin-babel":"^2.7.1",
"rollup-plugin-flow":"^1.1.1",
"rollup-plugin-replace":"^1.1.1",
"webpack":"^2.2.1",
"webpack-dev-middleware":"^1.10.1",
"webpack-hot-middleware":"^2.17.1",
"html-webpack-plugin":"^2.28.0",
"webpack-merge":"^4.0.0",
"write-file-webpack-plugin":"^4.0.0"},
"dependencies":{"node-ssh":"^4.0.1"}}