"UPDATE DATA: Fri Aug 25 2017 14:24:16 GMT+0800 (CST)" 
{
"name":"es6-magazine",
"version":"1.0.0-csp",
"description":"A es6-magazine project",
"scripts":{"dev":"node build/dev/index.js webpack-full-dev",
"dev:debug":"node build/dev/index.js webpack-full-debug",
"build":"node build/build/index.js compiler-full",
"online":"node build/test/online.js",
"release:download":"node build/release/index.js download",
"release:upload":"node build/release/index.js upload",
"svn":"node build/shell/svn.js",
"copy":"node build/copy/index.js",
"build:widget":"node build/build/compiler.widget.js",
"remote":"node build/remote/index.js",
"lint":"eslint dist/xxtppt.dev.js",
"unit":"karma start test/unit/karma.conf.js",
"karma":"karma start karma.conf.js --log-level debug --single-run",
"git":"bash build/shell/git.sh",
"ncu":"node build/ncu.package.js",
"format":"node build/format.js",
"check":"flow; test $? -eq 0 -o $? -eq 2",
"flow:check":"flow check"
},
"repository":{"type":"git",
"url":"git+https://github.com/JsAaron/node-magazine.git"},
"author":"Aaron",
"license":"ISC",
"bugs":{"url":"https://github.com/JsAaron/node-magazine/issues"},
"homepage":"https://github.com/JsAaron/node-magazine#readme",
"devDependencies":{"babel-eslint":"^7.2.3",
"babel-loader":"^7.1.2",
"babel-plugin-external-helpers":"^6.22.0",
"babel-plugin-transform-flow-strip-types":"^6.22.0",
"babel-preset-es2015":"^6.24.1",
"browser-sync":"^2.18.13",
"colors":"^1.1.2",
"eslint":"^4.5.0",
"eslint-config-standard":"^10.2.1",
"eslint-friendly-formatter":"^3.0.0",
"eslint-loader":"^1.9.0",
"eslint-plugin-html":"^3.2.0",
"eslint-plugin-promise":"^3.5.0",
"eslint-plugin-standard":"^3.0.1",
"eventsource-polyfill":"^0.9.6",
"express":"^4.15.4",
"flow-bin":"^0.53.1",
"fs-extra":"^4.0.1",
"gulp":"^3.9.1",
"gulp-autoprefixer":"^4.0.0",
"gulp-clean-css":"^3.7.0",
"gulp-concat":"^2.6.1",
"gulp-rename":"^1.2.2",
"gulp-tap":"^1.0.1",
"gulp-uglify":"^3.0.0",
"gulp-watch":"^4.3.11",
"html-webpack-plugin":"^2.30.1",
"node-ssh":"^4.2.3",
"npm-check-updates":"^2.12.1",
"open":"0.0.5",
"rollup":"^0.48.2",
"rollup-plugin-alias":"^1.3.1",
"rollup-plugin-babel":"^3.0.2",
"rollup-plugin-buble":"^0.15.0",
"rollup-plugin-flow":"^1.1.1",
"rollup-plugin-replace":"^1.1.1",
"ssh2":"^0.5.5",
"underscore":"^1.8.3",
"webpack":"^3.5.5",
"webpack-dev-middleware":"^1.12.0",
"webpack-hot-middleware":"^2.18.2",
"webpack-merge":"^4.1.0",
"write-file-webpack-plugin":"^4.1.0"}}